language: node_js
node_js:
  - "6"

install:
  - npm run bootstrap

cache:
  directories:
    - node_modules

script:
  - npm test

deploy:
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: "pixi-filters"
    skip_cleanup: true
    acl: public_read
    local_dir: filters/all/lib
    upload-dir: "$TRAVIS_BRANCH"
    cache_control: "max-age=60"
    region: eu-west-1
    on:
      all_branches: true
      condition: -z $TRAVIS_TAG 
  - provider: s3
    access_key_id: $S3_ACCESS_KEY_ID
    secret_access_key: $S3_SECRET_ACCESS_KEY
    bucket: "pixi-filters"
    skip_cleanup: true
    acl: public_read
    local_dir: filters/all/lib
    upload-dir: "$TRAVIS_BRANCH"
    cache_control: "max-age=2592000"
    region: eu-west-1
    on:
      all_branches: true
      condition: $TRAVIS_TAG
